#server:
#  port: 9192
spring:
#  h2:
#    console:
#      enabled: true
  
  application:
    name: KAFKA-CONSUMER-2
        
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#
#  instance:
#    hostname: localhost